# Learn more about services, parameters and containers at
# https://symfony.com/doc/current/service_container.html
parameters:
    #parameter_name: value

services:
    # default configuration for services in *this* file
    _defaults:
        # automatically injects dependencies in your services
        autowire: true
        # automatically registers your services as commands, event subscribers, etc.
        autoconfigure: true
        # this means you cannot fetch services directly from the container via $container->get()
        # if you need to do this, you can override this setting on individual services
        public: false
        bind:
            $userManager: '@fos_user.user_manager'

    # makes classes in src/AppBundle available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    MusicStudyBundle\:
        resource: '../../src/MusicStudyBundle/*'
        # you can exclude directories or files
        # but if a service is unused, it's removed anyway
        exclude: '../../src/MusicStudyBundle/{Entity,Repository,Tests}'

    # controllers are imported separately to make sure they're public
    # and have a tag that allows actions to type-hint services
    MusicStudyBundle\Controller\:
        resource: '../../src/MusicStudyBundle/Controller'
        public: true
        tags: ['controller.service_arguments']

    pagerfanta.view.task_view:
        class: 'Pagerfanta\View\OptionableView'
        arguments:
            - '@pagerfanta.view.default'
            - { proximity: 3, prev_message: 'Prec.', next_message: 'Suiv.' }
        public: false
        tags: [{ name: pagerfanta.view, alias: task_view }]